---
groups:
  - name: certify-aws
    jobs:
      - bats-centos-7
      - bats-ubuntu-xenial
      - test-stemcell-ubuntu-xenial
      - end2end-us
      - test-upgrade
      - certify-centos-7
      - certify-ubuntu-xenial

shared:
  - &prepare-director
    task: prepare-director
    file: pipelines/shared/tasks/prepare-director.yml
    params: &prepare-director-params
      INFRASTRUCTURE:     aws
      DIRECTOR_VARS_FILE: {{aws_director_vars_file}}
      OPTIONAL_OPS_FILE: |
        -o bosh-deployment/external-ip-with-registry-not-recommended.yml
        -o pipelines/shared/assets/ops/remove-provider-cert.yml

  - &prepare-director-xenial
    task: prepare-director
    file: pipelines/shared/tasks/prepare-director.yml
    params: &prepare-director-params
      INFRASTRUCTURE:     aws
      DIRECTOR_VARS_FILE: {{aws_director_vars_file}}
      OPTIONAL_OPS_FILE: |
        -o bosh-deployment/external-ip-with-registry-not-recommended.yml
        -o pipelines/shared/assets/ops/remove-provider-cert.yml

  - &deploy-director
    task: deploy-director
    file: pipelines/shared/tasks/deploy-director.yml

  - &run-bats
    task: run-bats
    file: pipelines/shared/tasks/run-bats.yml
    params: &run-bats-params
      INFRASTRUCTURE:     aws
      BAT_INFRASTRUCTURE: aws
      BAT_RSPEC_FLAGS:    "--tag ~multiple_manual_networks --tag ~root_partition"

  - &test-stemcell-ubuntu-xenial
    task: test-stemcell-ubuntu-xenial
    file: pipelines/shared/tasks/test-stemcell.yml
    params:
      BOSH_os_name: ubuntu-xenial
      package: ipv4director

  - &update-cloud-config
    task: update-cloud-config
    file: pipelines/shared/tasks/update-cloud-config.yml
    params: &update-cloud-config-params
      INFRASTRUCTURE: aws
      DIRECTOR_VARS_FILE: {{aws_director_vars_file}}

  - &run-end-2-end
    task: run-e2e
    file: bosh-cpi-src/ci/tasks/run-e2e.yml
    params:
      BOSH_AWS_KMS_KEY_ARN: {{aws_kms_key_arn}}

  - &teardown
    task: teardown
    file: pipelines/shared/tasks/teardown.yml

jobs:
  - name: test-stemcell-ubuntu-xenial
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,                trigger: true}
        - {get: cpi-release,                 trigger: true}
        - {get: stemcell,                    trigger: true, resource: ubuntu-xenial-stemcell}
        - {get: after-midnight,              trigger: true}
        - {get: pipelines,                   trigger: false}
        - {get: bosh-cli,                    trigger: false}
        - {get: bats,                        trigger: false}
        - {get: bosh-deployment,             trigger: false}
        - {get: syslog-release,              trigger: false}
        - {get: os-conf-release,             trigger: false}
        - {get: bosh-linux-stemcell-builder, trigger: false}
      - put: environment
        params:
          env_name: aws-test-stemcell-ubuntu-xenial
          delete_on_failure: true
          generate_random_name: true
          terraform_source: pipelines/aws/assets/terraform
      - do:
        - <<: *prepare-director
          params:
            <<: *prepare-director-params
            OPTIONAL_OPS_FILE: |
              -o pipelines/shared/assets/ops/remove-hm.yml
              -o bosh-deployment/external-ip-with-registry-not-recommended.yml
              -o pipelines/shared/assets/ops/remove-provider-cert.yml
        - do:
          - <<: *deploy-director
          - <<: *update-cloud-config
          - <<: *test-stemcell-ubuntu-xenial
          ensure:
            do:
              - <<: *teardown
        ensure:
          do:
            - put: environment
              params:
                env_name: certify-aws-test-stemcell-ubuntu-xenial
                action: destroy
                env_name_file: environment/name
                terraform_source: pipelines/aws/assets/terraform
              get_params:
                action: destroy

  - name: end2end-us
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,           trigger: true}
        - {get: cpi-release,            trigger: true}
        - {get: after-midnight,         trigger: true}
        - {get: centos-7-stemcell,      trigger: false} # pass-thru to certification jobs
        - {get: pipelines,              trigger: false}
        - {get: bosh-cli,               trigger: false}
        - {get: bosh-deployment,        trigger: false}
        - {get: bosh-cpi-src,           trigger: false}
        - get: heavy-stemcell
          resource: heavy-ubuntu-xenial-stemcell
          params:
            preserve_filename: true
        - get: stemcell
          resource: ubuntu-xenial-stemcell
          trigger: true
          params:
            preserve_filename: true
      - put: environment
        params:
          env_name: certify-aws-end2end-us
          delete_on_failure: true
          generate_random_name: true
          terraform_source: pipelines/aws/assets/terraform
      - do:
        - <<: *prepare-director
          params:
            <<: *prepare-director-params
            OPTIONAL_OPS_FILE:  |
              -o bosh-deployment/external-ip-with-registry-not-recommended.yml
              -o pipelines/shared/assets/ops/remove-provider-cert.yml
              -o pipelines/aws/assets/ops/iam-instance-profile-ops-file.yml
        - do:
            - <<: *deploy-director
            - <<: *run-end-2-end
          ensure:
            do:
              - <<: *teardown
        ensure:
          do:
            - put: environment
              params:
                env_name: certify-aws-end2end-us
                action: destroy
                env_name_file: environment/name
                terraform_source: pipelines/aws/assets/terraform
              get_params:
                action: destroy

  - name: bats-centos-7
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,    trigger: true}
        - {get: cpi-release,     trigger: true}
        - {get: after-midnight,  trigger: true}
        - {get: pipelines,       trigger: false}
        - {get: bosh-cli,        trigger: false}
        - {get: bats,            trigger: false}
        - {get: bosh-deployment, trigger: false}
        - get: ubuntu-xenial-stemcell
        - get: stemcell
          resource: centos-7-stemcell
          trigger: true
          params:
            preserve_filename: true
      - put: environment
        params:
          env_name: certify-aws-bats-centos-7
          delete_on_failure: true
          generate_random_name: true
          terraform_source: pipelines/aws/assets/terraform
      - do:
        - <<: *prepare-director
          params:
            <<: *prepare-director-params
            OPTIONAL_OPS_FILE:  |
              -o pipelines/shared/assets/ops/remove-hm.yml
              -o bosh-deployment/external-ip-with-registry-not-recommended.yml
              -o pipelines/shared/assets/ops/remove-provider-cert.yml
          input_mapping:
            stemcell: ubuntu-xenial-stemcell
        - do:
          - <<: *deploy-director
            input_mapping:
              stemcell: ubuntu-xenial-stemcell
          - <<: *run-bats
            params:
              <<: *run-bats-params
              STEMCELL_NAME: bosh-aws-xen-hvm-centos-7-go_agent
          ensure:
            do:
              - <<: *teardown
        ensure:
          do:
            - put: environment
              params:
                env_name: certify-aws-bats-centos-7
                action: destroy
                env_name_file: environment/name
                terraform_source: pipelines/aws/assets/terraform
              get_params:
                action: destroy

  - name: bats-ubuntu-xenial
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,    trigger: true}
        - {get: cpi-release,     trigger: true}
        - {get: after-midnight,  trigger: true}
        - {get: pipelines,       trigger: false}
        - {get: bosh-cli,        trigger: false}
        - {get: bats,            trigger: false}
        - {get: bosh-deployment, trigger: false}
        - get: stemcell
          resource: ubuntu-xenial-stemcell
          trigger: true
          params:
            preserve_filename: true
      - put: environment
        params:
          env_name: certify-aws-bats-ubuntu-xenial
          delete_on_failure: true
          generate_random_name: true
          terraform_source: pipelines/aws/assets/terraform
      - do:
        - <<: *prepare-director
          params:
            <<: *prepare-director-params
            OPTIONAL_OPS_FILE:  |
              -o pipelines/shared/assets/ops/remove-hm.yml
              -o bosh-deployment/external-ip-with-registry-not-recommended.yml
              -o pipelines/shared/assets/ops/remove-provider-cert.yml
        - do:
          - <<: *deploy-director
          - <<: *run-bats
            params:
              <<: *run-bats-params
              STEMCELL_NAME: bosh-aws-xen-hvm-ubuntu-xenial-go_agent
          ensure:
            do:
              - <<: *teardown
        ensure:
          do:
            - put: environment
              params:
                env_name: certify-aws-bats-ubuntu-xenial
                action: destroy
                env_name_file: environment/name
                terraform_source: pipelines/aws/assets/terraform
              get_params:
                action: destroy

  - name: test-upgrade
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,            trigger: true}
        - {get: cpi-release,             trigger: true}
        - {get: after-midnight,          trigger: true}
        - {get: pipelines,               trigger: false}
        - {get: bosh-cli,                trigger: false}
        - {get: centos-7-stemcell,       trigger: false} # pass-through
        - {get: old-bosh-release,        trigger: false}
        - {get: old-cpi-release,         trigger: false}
        - {get: bosh-deployment,         trigger: false}
        - get: new-stemcell
          resource: ubuntu-xenial-stemcell
          trigger: true
          params:
            preserve_filename: true
        - get: old-stemcell
          trigger: false
          params:
            preserve_filename: true
      - put: environment
        params:
          env_name: certify-aws-test-upgrade
          delete_on_failure: true
          generate_random_name: true
          terraform_source: pipelines/aws/assets/terraform
      - <<: *prepare-director
        input_mapping:
          stemcell:     old-stemcell
          bosh-release: old-bosh-release
          cpi-release:  old-cpi-release
        params:
          <<: *prepare-director-params
          OPTIONAL_OPS_FILE: |
            -o bosh-deployment/external-ip-with-registry-not-recommended.yml
            -o pipelines/shared/assets/ops/remove-provider-cert.yml
      - do:
        - <<: *deploy-director
          input_mapping:
            stemcell:     old-stemcell
            bosh-release: old-bosh-release
            cpi-release:  old-cpi-release
        - <<: *update-cloud-config
        - task: create-deployment
          file: pipelines/shared/tasks/create-deployment.yml
          input_mapping:
            stemcell: old-stemcell
          params:
            INFRASTRUCTURE: aws
            STEMCELL_NAME:  bosh-aws-xen-hvm-ubuntu-xenial-go_agent
        - <<: *prepare-director
          input_mapping:
            stemcell: new-stemcell
        - task: test-upgrade
          file: pipelines/shared/tasks/test-upgrade.yml
          input_mapping:
            stemcell: new-stemcell
            old-director-state:  director-state
            new-director-config: director-config
          output_mapping:
            new-director-state:  director-state
        ensure:
          do:
            - <<: *teardown
            - put: environment
              params:
                env_name: certify-aws-test-upgrade
                action: destroy
                env_name_file: environment/name
                terraform_source: pipelines/aws/assets/terraform
              get_params:
                action: destroy

  - name: certify-centos-7
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release, trigger: true, passed: [bats-centos-7, end2end-us]}
        - {get: cpi-release,  trigger: true, passed: [bats-centos-7, end2end-us]}
        - {get: stemcell,     trigger: true, passed: [bats-centos-7, end2end-us, test-upgrade], resource: centos-7-stemcell}
        - {get: pipelines,    trigger: false}
      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        params:
          CPI_RELEASE_NAME: bosh-aws-cpi
          STEMCELL_NAME:    bosh-aws-xen-hvm-centos-7-go_agent
      - {put: receipt, params: {file: certification/*-receipt.json}}

  - name: certify-ubuntu-xenial
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release, trigger: true, passed: [bats-ubuntu-xenial, end2end-us]}
        - {get: cpi-release,  trigger: true, passed: [bats-ubuntu-xenial, end2end-us]}
        - {get: stemcell,     trigger: true, passed: [bats-ubuntu-xenial, end2end-us, test-upgrade, test-stemcell-ubuntu-xenial], resource: ubuntu-xenial-stemcell}
        - {get: pipelines,    trigger: false}
      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        params:
          CPI_RELEASE_NAME: bosh-aws-cpi
          STEMCELL_NAME:    bosh-aws-xen-hvm-ubuntu-xenial-go_agent
      - {put: receipt, params: {file: certification/*-receipt.json}}

resource_types:
  - name: terraform_type
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource

resources:
  - name: after-midnight
    type: time
    source:
      start: 12:00 AM -0700
      stop: 2:00 AM -0700
  - name: bosh-cpi-src
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release.git
      branch: master
      paths:
        - ci/**
  - name: pipelines
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-cpi-certification
      branch: master
  - name: bosh-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment
      branch: master
  - name: cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-aws-cpi-release
  - name: old-cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-aws-cpi-release
      regexp: 72
  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh
  - name: old-bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh
      regexp: 267.*
  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: master
  - name: heavy-ubuntu-xenial-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-xenial-go_agent
      force_regular: true
  - name: old-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-xenial-go_agent
      version_family: 97.latest
  - name: centos-7-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-centos-7-go_agent
      force_regular: true
  - name: ubuntu-xenial-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-xenial-go_agent
  - name: bosh-cli
    type: s3
    source:
      regexp: bosh-cli-([0-9.]+)-linux-amd64
      cloudfront_url: https://dulfnruy35dwq.cloudfront.net
      bucket: bosh-cli-artifacts
      region_name: us-east-1
  - name: receipt
    type: s3
    source:
      access_key_id: {{certification__bucket_access_key}}
      secret_access_key: {{certification__bucket_secret_key}}
      bucket: {{certification__bucket}}
      regexp: .*-(\d+)-receipt\.json
      region_name: us-east-1
  - name: environment
    type: terraform_type
    source:
      storage:
        access_key_id:     {{terraform_aws_access_key}}
        secret_access_key: {{terraform_aws_secret_key}}
        bucket:            {{terraform_bucket}}
        bucket_path:       terraform-state
      vars:
        access_key: {{AWS_ACCESS_KEY}}
        secret_key: {{AWS_SECRET_KEY}}
        region:     {{AWS_REGION_NAME}}
        public_key: {{PUBLIC_KEY}}
  - name: bosh-linux-stemcell-builder
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-linux-stemcell-builder
      branch: master
  - name: syslog-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/syslog-release
  - name: os-conf-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/os-conf-release
