---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bosh/integration, tag: main }

inputs:
  - name: pipelines
  - name: environment
  - name: director-state
  - name: stemcell
  - name: bosh-cli

run:
  path: pipelines/shared/tasks/create-deployment.sh

params:
  VCENTER_NETWORK_NAME: ""
  INFRASTRUCTURE:       ""
  DEPLOYMENT_NAME:      certification
  RELEASE_NAME:         certification
  STEMCELL_NAME:        ""
