---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bosh/integration, tag: main }

inputs:
  - name: bosh-release
  - name: cpi-release
  - name: stemcell
  - name: pipelines
outputs:
  - name: certification

run:
  path: pipelines/shared/tasks/generate-receipt.sh

params:
  CPI_RELEASE_NAME: ""
  STEMCELL_NAME:    ""
