---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bosh/integration, tag: main }

inputs:
  - name: pipelines
  - name: environment
  - name: bats
  - name: director-state
  - name: stemcell

run:
  path: pipelines/shared/tasks/run-bats.sh

params:
  INFRASTRUCTURE:     ""
  STEMCELL_NAME:      ""
  BAT_INFRASTRUCTURE: ""
  BAT_RSPEC_FLAGS:    ""
  RUBY_VERSION: 2.4.4
