---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bosh/integration, tag: main }

inputs:
  - name: pipelines
  - name: director-state
  - name: bosh-cli

run:
  path: pipelines/shared/tasks/teardown.sh
params:
  RUBY_VERSION: 2.4.4
